# Config file for automatic testing at travis-ci.org
# sudo: required
language: cpp
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev  
script:
  - $CXX --version
  - g++ --version
  - qmake -v
  # - qmake -project "CONFIG += c++11" "DESTDIR = build" "QT += core gui widgets"
  - qmake -project "CONFIG += c++11" "DESTDIR = build" "QT += gui"
  - qmake
  - cat Qt5HelloWorld.pro
  - cat Makefile
  - make
