# Config file for automatic testing at travis-ci.org
language: cpp
# compiler: clang
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq qt5-default qttools5-dev-tools
  # - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev
before_script:
  - QTDIR="/usr/lib/x86_64-linux-gnu/qt5"
  - PATH="$QTDIR/bin:$PATH"
script:
  - $CXX --version
  - g++ --version
  - qmake -v
  - mkdir build && cd build && qmake -project "CONFIG += c++11" "QT += widgets" ..
  - qmake
  - cat Qt5HelloWorld.pro
  - cat Makefile
  - make
